// Generated by Home Manager.



user_pref("browser.bookmarks.file", "/nix/store/j9af191rf1vhj4r996giy57bin3jma21-bookmarks.html");
user_pref("browser.places.importBookmarksHTML", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);


// userchrome.css usercontent.css activate
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// Fill SVG Color
user_pref("svg.context-properties.content.enabled", true);

// CSS's `:has()` selector 
user_pref("layout.css.has-selector.enabled", true);

