git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
# gui:
#   theme:
#     activeBorderColor:
#       - '#b4befe'
#       - bold
#     inactiveBorderColor:
#       - '#a6adc8'
#     optionsTextColor:
#       - '#89b4fa'
#     selectedLineBgColor:
#       - '#313244'
#     selectedRangeBgColor:
#       - '#313244'
#     cherryPickedCommitBgColor:
#       - '#45475a'
#     cherryPickedCommitFgColor:
#       - '#b4befe'
#     unstagedChangesColor:
#       - '#f38ba8'
#     defaultFgColor:
#       - '#cdd6f4'
#     searchingActiveBorderColor:
#       - '#f9e2af'
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"
