# Import themes
general.import = ["~/.config/alacritty/tokyonight_moon.toml"]

[terminal.shell]
program = "/usr/bin/zsh"
# args = ["-l", "-c", "tmux"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dimensions = { columns = 150, lines = 40 } 
dynamic_padding = true
padding = { x = 10, y = 10 }
position = { "x" = 100, "y" = 20 }
opacity = 0.99

[font]
normal.family = "OverpassM Nerd Font"
bold.family = "SpaceMono Nerd Font"
italic.family = "SpaceMono Nerd Font"
bold_italic.family = "SpaceMono Nerd Font"
size = 15

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
  { key = "+", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },
  { key = "t", mods = "Alt|Shift", chars = "alacritty msg config window.opacity=0.95" },
  { key = "o", mods = "Alt|Shift", chars = "alacritty msg config window.opacity=1.0" },
  { key = "]", mods = "Alt", action = "ToggleMaximized" },
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]
