import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/usr/bin/zsh"
# args = ["-l", "-c", "tmux"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
# decorations = "None"
dimensions = { columns = 110, lines = 30 }
dynamic_padding = true
position = { "x" = 100, "y" = 20 }
opacity = 0.93

[font]
normal.family = "JetBrainsMono NF"
bold.family = "JetBrainsMono NF"
italic.family = "JetBrainsMono NF"
bold_italic.family = "JetBrainsMono NF"
size = 16.5

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
  { key = "+", mods="Control", action = "IncreaseFontSize" },
  { key = "-", mods="Control", action = "DecreaseFontSize" },
  { key = "0", mods="Control", action = "ResetFontSize" },
  { key = "]", mods="Alt", action = "ToggleMaximized" },
  { key = "Return", mods="Alt", action = "ToggleFullscreen" },
]
