# import = ["~/.config/alacritty/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/tokyonight_moon.toml"]
# import = ["~/.config/alacritty/tokyonight_storm.toml"]
# import = ["~/.config/alacritty/tokyonight_night.toml"]

[shell]
program = "/usr/bin/zsh"
# args = ["-l", "-c", "tmux"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dimensions = { columns = 110, lines = 30 }
dynamic_padding = true
position = { "x" = 100, "y" = 20 }
opacity = 0.95

[font]
normal.family = "SpaceMono Nerd Font"
bold.family = "SpaceMono Nerd Font"
italic.family = "SpaceMono Nerd Font"
bold_italic.family = "SpaceMono Nerd Font"
# normal.family = "JetBrainsMono NF"
# normal.style = 'medium'
# bold.family = "JetBrainsMono NF"
# italic.family = "JetBrainsMono NF"
# bold_italic.family = "JetBrainsMono NF"
size = 14

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
  { key = "+", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },
  { key = "t", mods = "Alt|Shift", chars = "alacritty msg config window.opacity=0.93" },
  { key = "o", mods = "Alt|Shift", chars = "alacritty msg config window.opacity=1.0" },
  { key = "]", mods = "Alt", action = "ToggleMaximized" },
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]
