version = 2
console_title_template = '{{if .Root}}(Admin) {{end}}{{.Folder}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    template = ''
    background = '#f1184c'
    foreground = '#242424'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    leading_diamond = ' '
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    background = '#282c34'
    foreground = '#3A86FF'

  [[blocks.segments]]
    type = 'time'
    style = 'powerline'
    powerline_symbol = ''
    template = '{{ .CurrentDate | date .Format }} '
    background = '#242424'
    foreground = '#FFBB00'

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .Path }} '
    background = '#242424'
    foreground = '#33DD2D'

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background = '#242424'
    foreground = '#3A86FF'

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'dotnet'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} '
    background = '#0184bc'
    foreground = '#ffffff'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    template = ' <#fefefe></> {{ .FormattedMs }} '
    background = '#8800dd'
    foreground = '#ffffff'

    [blocks.segments.properties]
      style = 'austin'
      threshold = 1.0

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    template = '  '
    background = '#33DD2D'
    foreground = '#242424'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '➜ '
    foreground = '#f1184c'
