version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = '#5E81AC'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    foreground = '#668cbe'

    [blocks.segments.properties]
      style = 'agnoster_full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '<#787c99>::</> {{ .HEAD }} {{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</> '
    # template = '<#787c99>::</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }} {{ if gt .StashCount 0 }}{{ .StashCount }}  {{ end }} '
    foreground = '#7aa2f7'

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  overflow = 'hidden'
  alignment = "right"

  [[blocks.segments]]
  type = "yarn"
  style = "powerline"
  foreground = "#c0caf5"
  template = "󰄛 {{ .Full }} <#787c99>::</> "

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} <#787c99>::</> '
    foreground = '#41a6b5'

  [[blocks.segments]]
  type = "kubectl"
  style = "powerline"
  foreground = "#7dcfff"
  template = "{{if .Namespace}}{{.Namespace}}@{{end}}{{.Context}} "

    [properties.context_aliases]
    "arn:aws:eks:eu-west-1:1234567890:cluster/posh" = "posh"

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#414868'
    template = '<#787c99>::</> {{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 1000
      style = "round"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}#f7768e{{end}}",
      "{{if eq .Code 0}}#bb9af7{{end}}",
    ]
  template = ' ➜'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  template = ' ➜ '
  # WIP: https://github.com/JanDeDobbeleer/oh-my-posh/issues/4822
  # [[blocks.segments]]
  #   type = 'time'
  #   style = 'powerline'
  #   powerline_symbol = ''
  #   template = '{{ .CurrentDate | date .Format }} '
  #   foreground = '#414868'
  #
  #   [blocks.segments.properties]
  #     time_format = '15:04:05'


[secondary_prompt]
  foreground = '#bb9af7'
  template = ' ➜➜ '

# [[blocks]]
#   type = 'prompt'
#   alignment = 'left'
#   newline = true
#
#   [[blocks.segments]]
#     type = 'status'
#     style = 'powerline'
#     foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']
#     template = ' # '
#     foreground = '#4691ff'
#
#     [blocks.segments.properties]
#       always_enabled = true
