#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = " {{ .Folder }} :: {{if .Root}}Admin{{end}}"
final_space = true
terminal_background = "p:t-background"
version = 2.0

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
background = "transparent"
foreground = "p:terminal-blue"
style = "plain"
template = "➜ "
type = "text"

[[blocks.segments]]
foreground = "p:terminal-magenta"
style = "plain"
template = "<b>{{ .Path }}</b> <p:light-sky-blue>⚡</>"
type = "path"
[blocks.segments.properties]
style = "full"

[[blocks.segments]]
foreground = "p:light-sky-blue"
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}",
  "{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}",
  "{{ if gt .Behind 0 }}p:celeste-blue{{ end }}",
]
style = "plain"
template = "({{ .HEAD}})"
type = "git"
[blocks.segments.properties]
branch_icon = "\ue725 "
fetch_status = true

[[blocks.segments]]
foreground = "p:terminal-red"
style = "plain"
template = " \uf00d"
type = "status"

[[blocks]]
alignment = "right"
overflow = "hide"
type = "prompt"

[[blocks.segments]]
foreground = "p:pistachio-green"
style = "plain"
template = "\ue718 {{ .Full }} "
type = "node"

[[blocks.segments]]
foreground = "p:terminal-blue"
style = "plain"
template = "\ue73d {{ .Full }} "
type = "php"

[[blocks.segments]]
foreground = "p:terminal-yellow"
style = "plain"
template = "\ue235 {{ .Full }}"
type = "python"

[[blocks.segments]]
foreground = "p:terminal-magenta"
style = "plain"
template = "\ue624 {{ .Full }}"
type = "julia"

[[blocks.segments]]
foreground = "p:terminal-red"
style = "plain"
template = "\ue791 {{ .Full}}"
type = "ruby"

[[blocks.segments]]
foreground = "p:light-sky-blue"
style = "plain"
template = "\ufcd1 {{ .Full}}"
type = "go"

[[blocks.segments]]
foreground = "p:white-blue"
style = "plain"
type = "command"
[blocks.segments.properties]
command = "git log --pretty=format:%cr -1 || date +%H:%M:%S"
shell = "bash"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "p:pistachio-green"
style = "plain"
template = "\u25b6"
type = "text"

[palette]
blue-bell = "#9aa5ce"
blue-black = "#565f89"
celeste-blue = "#b4f9f8"
light-sky-blue = "#7dcfff"
main-bg = "#24283b"
pastal-grey = "#cfc9c2"
pistachio-green = "#9ece6a"
t-background = "p:main-bg"
terminal-black = "#414868"
terminal-blue = "#7aa2f7"
terminal-green = "#73daca"
terminal-magenta = "#bb9af7"
terminal-red = "#f7768e"
terminal-white = "#c0caf5"
terminal-yellow = "#e0af68"
white-blue = "#a9b1d6"

[secondary_prompt]
background = "transparent"
foreground = "p:terminal-blue"
template = "➜ "

[transient_prompt]
background = "p:t-background"
foreground = "p:terminal-blue"
template = "➜ "
