#Location: ~/.config/starship.toml
#What_is_starship: https://starship.rs/

add_newline = true
command_timeout = 2000

format = """$env_var$os$directory$git_branch$git_status$kubernetes$nodejs$python
$character
"""

[character]
success_symbol = '[➜](bold fg:#414868)'
error_symbol = '[✗](bold fg:#f7768e)'
vimcmd_symbol = '[V](bold green)'

[env_var]
symbol = ""
variable = 'SHELL'
format = "$symbol"
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'

[os]
format = '[$symbol](bold fg:#73daca) '
disabled = false

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false
style = 'bold fg:#73daca'

# Shows current git branch
[git_branch]
format = '[|](bold fg:#414868) [$symbol$branch(:$remote_branch)]($style) '
disabled = false
style = 'bold fg:#bb9af7'

# Shows current git status
[git_status]
disabled = false
style = 'bold fg:#bb9af7'

# Shows kubernetes context and namespace
[kubernetes]
format = '[|](bold fg:#414868) [󱃾 $context](bold #7aa2f7) '
disabled = false

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true

# Shows the username
[username]
disabled = true

# Shows the hostname
[hostname]
disabled = true
